AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    Description: Environment stage or git branch

  LogRetentionInDays:
    Type: Number
    Default: 14
    Description: CloudWatch Logs retention period

  SharedLibsLayer:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Project shared libraries Lambda Layer ARN

Globals:
  Function:
    Timeout: 10
    Tracing: Active
    MemorySize: 512
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: payment
        POWERTOOLS_METRICS_NAMESPACE: ServerlessAirline
        LOG_LEVEL: INFO

Resources:
#  StripePaymentApplication:
#    Type: AWS::Serverless::Application
#    Properties:
#      Location:
#        ApplicationId: arn:aws:serverlessrepo:us-east-1:375983427419:applications/api-lambda-stripe-charge
#        SemanticVersion: 4.4.2
#      Parameters:
#        EnableInstantCapture: "false"
#        SSMParameterPath: !Sub ${Stage}/service/payment/stripe/secretKey

  PaymentApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowMethods: "'*'"
        AllowOrigin: "'*'"
      MethodSettings:
        - ResourcePath: /charge
          HttpMethod: post
        - ResourcePath: /capture
          HttpMethod: post
        - ResourcePath: /refund
          HttpMethod: post

  PaymentCharge:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ServerlessAirline-PaymentCharge-${Stage}
      Handler: charge.lambda_handler
      Runtime: python3.8
      CodeUri: src/payment-charge
      Layers:
        - !Ref SharedLibsLayer
      Environment:
        Variables:
          STAGE: !Ref Stage
      Events:
        ApiEvent:
            Type: Api
            Properties:
              Path: /charge
              Method: post
              RestApiId:
                Ref: PaymentApi

  PaymentCapture:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ServerlessAirline-PaymentCapture-${Stage}
      Handler: capture.lambda_handler
      Runtime: python3.8
      CodeUri: src/payment-capture
      Layers:
        - !Ref SharedLibsLayer
      Environment:
        Variables:
          STAGE: !Ref Stage
      Events:
        ApiEvent:
            Type: Api
            Properties:
              Path: /capture
              Method: post
              RestApiId:
                Ref: PaymentApi

  PaymentRefund:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ServerlessAirline-PaymentRefund-${Stage}
      Handler: capture.lambda_handler
      Runtime: python3.8
      CodeUri: src/payment-refund
      Layers:
        - !Ref SharedLibsLayer
      Environment:
        Variables:
          STAGE: !Ref Stage
      Events:
        ApiEvent:
            Type: Api
            Properties:
              Path: /refund
              Method: post
              RestApiId:
                Ref: PaymentApi

  CollectPayment:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ServerlessAirline-CollectPayment-${Stage}
      Handler: collect.lambda_handler
      Runtime: python3.8
      CodeUri: src/collect-payment
      Layers:
        - !Ref SharedLibsLayer
      Environment:
        Variables:
          PAYMENT_API_URL: !Sub 'https://${PaymentApi}.execute-api.${AWS::Region}.amazonaws.com/prod/capture'
          STAGE: !Ref Stage

  RefundPayment:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ServerlessAirline-RefundPayment-${Stage}
      Handler: refund.lambda_handler
      CodeUri: src/refund-payment
      Runtime: python3.8
      Layers:
        - !Ref SharedLibsLayer
      Environment:
        Variables:
          PAYMENT_API_URL: !Sub 'https://${PaymentApi}.execute-api.${AWS::Region}.amazonaws.com/prod/refund'
          STAGE: !Ref Stage

  PaymentChargeLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${PaymentCharge}"
      RetentionInDays: !Ref LogRetentionInDays

  PaymentCaptureLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${PaymentCapture}"
      RetentionInDays: !Ref LogRetentionInDays

  PaymentRefundLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${PaymentRefund}"
      RetentionInDays: !Ref LogRetentionInDays

  RefundPaymentLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${RefundPayment}"
      RetentionInDays: !Ref LogRetentionInDays

  CollectPaymentLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${CollectPayment}"
      RetentionInDays: !Ref LogRetentionInDays

  CollectPaymentParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub /${Stage}/service/payment/function/collect
      Description: Collect Payment Lambda ARN
      Type: String
      Value: !Sub ${CollectPayment.Arn}

  RefundPaymentParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub /${Stage}/service/payment/function/refund
      Description: Refund Payment Lambda ARN
      Type: String
      Value: !Sub ${RefundPayment.Arn}

  PaymentCaptureEndpointParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${Stage}/service/payment/api/capture/url"
      Type: String
      Value: !Sub 'https://${PaymentApi}.execute-api.${AWS::Region}.amazonaws.com/prod/capture'

  PaymentChargeEndpointParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${Stage}/service/payment/api/charge/url"
      Type: String
      Value: !Sub 'https://${PaymentApi}.execute-api.${AWS::Region}.amazonaws.com/prod/charge'

  PaymentRefundEndpointParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${Stage}/service/payment/api/refund/url"
      Type: String
      Value: !Sub 'https://${PaymentApi}.execute-api.${AWS::Region}.amazonaws.com/prod/refund'

Outputs:
  CollectPaymentFunction:
    Value: !Sub ${CollectPayment.Arn}
    Description: Collect Payment Lambda Function

  RefundPaymentFunction:
    Value: !Sub ${RefundPayment.Arn}
    Description: Refund Payment Lambda Function

  PaymentCaptureUrl:
    Value: !Sub 'https://${PaymentApi}.execute-api.${AWS::Region}.amazonaws.com/prod/capture'
    Description: Payment Endpoint for capturing payments

  PaymentChargeUrl:
    Value: !Sub 'https://${PaymentApi}.execute-api.${AWS::Region}.amazonaws.com/prod/charge'
    Description: Payment Endpoint for collecting payments

  RefundApiUrl:
    Value: !Sub 'https://${PaymentApi}.execute-api.${AWS::Region}.amazonaws.com/prod/refund'
    Description: Payment Endpoint for refunding payments
